
dataset:
  type: blender
  root: ./data/nerf_synthetic/lego

no_batching: True
use_viewdirs: True
white_bg: True
lr_decay: 500

n_samples: 64
n_importance: 128
n_rand: 1024

precrop_iters: 500
precrop_frac: 0.5
half_res: True
